name: Tests

on:
  push:
    # We intentionally don't run push on feature branches. See PR for rational.
    branches: [master]
  pull_request:
  workflow_dispatch:

jobs:
  tests-main:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [18]
    steps:
      # <common-build> - Uses YAML anchors in the future
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node}}
      - name: Node.js version
        id: node
        run: echo "v8CppApiVersion=$(node --print "process.versions.modules")" >> $GITHUB_OUTPUT
      - name: Confirm output from node
        run: echo "v8CppApiVersion is ${{ steps.node.outputs.v8CppApiVersion }}"
      - name: Set output in shell script
        id: validate_rc
        run: scripts/assert_valid_rc.sh
      - name: Confirm output from validate_rc
        run: |
          echo "is_rc is ${{ steps.validate_rc.outputs.is_rc }} version is ${{ steps.validate_rc.outputs.version }}"
          echo "current branch is ${GITHUB_REF}"
      - name: Set output in js
        id: get_prev_tag
        run: node scripts/get_prev_tag.js
      - name: Confirm output from js script
        run: echo "prev_tag is ${{ steps.get_prev_tag.outputs.prev_tag }}"
      - name: Install & build
        run: yarn install
      # </common-build>

      - name: Unit test
        run: yarn test:unit
